# Extends the C++ class Slic3r::Layer.

package Slic3r::Layer;
use strict;
use warnings;

# the following two were previously generated by Moo
sub print {
    my $self = shift;
    return $self->object->print;
}

sub config {
    my $self = shift;
    return $self->object->config;
}

1;
