name: C/C++ dev macos

on:
  push:
    branches:
      - Main
      - nightly_dev
      - nightly_master
      - debug_macos
      - dev
      - supermerill-Main
jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: install build tools
      run: brew install autoconf automake libtool
    - name: check autoconf version
      run: autoconf --version
    - name: build deps & slicer
      run: ./BuildMacOS.sh -dsi
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}_patch_01.app
        path: build/pack/${{ github.event.repository.name }}/${{ github.event.repository.name }}.app
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}_patch_01.dmg
        path: ${{ github.event.repository.name }}.dmg
