name: Build

on:
  push:
    branches:
      - Main
      - nightly_dev
      - nightly_master
      - debug_macos
      - dev
      - supermerill-Main
      - rc


jobs:
  build_osx:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_osx.yml@master
    secrets: inherit

  build_osx_asan:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_osx.yml@master
    secrets: inherit
    needs: build_osx
    with:
      with_asan: true

  build_win:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_windows.yml@master
    secrets: inherit

  build_flatpak:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_flatpak.yml@master
    secrets: inherit

  build_flatpak_asan:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_flatpak.yml@master
    secrets: inherit
    needs: build_flatpak
    with:
      with_asan: true
