name: C/C++ debug ubuntu

on:
  push:
    branches:
      - debug_ubuntu

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'debug_ubuntu'
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.16.x'
    - name: change date in version
      run: sed -i "s/+UNKNOWN/_$(date '+%F')/" version.inc
    - name: update clock
      run: sudo hwclock -s
    - name: update apt
      run: sudo apt update
    - name: install gtk2 glew
      run: sudo apt install libgtk2.0-dev libglew-dev libudev-dev libdbus-1-dev libssl-dev libcurl4-openssl-dev gettext
    - name: build deps & slicer, tar & appimage
      run: ./BuildLinux.sh -bdgsi
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_linux_gtk2.tar
        path: build/${{ github.event.repository.name }}.tar
    - name: Upload appimage
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ github.event.repository.name }}-gtk2.AppImage
        path: build/${{ github.event.repository.name }}_ubu64.AppImage
