name: C/C++ test ubuntu

on:
  push:
    branches:
      - dev
      - debug_ubuntu

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.16.x'
    - name: update apt
      run: sudo apt update
    - name: install test deps
      run: sudo apt install libgtk2.0-dev libglew-dev libudev-dev libdbus-1-dev gettext
    - name: build with tests
      run: ./BuildLinux.sh -dgti
